### ISSUE TITLE
The sensor variable not defined in documentation

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/Reactive.jl#36]
Starting in the __Example: A stupid line-droid__ section.

**Comment by milktrader** [comment]
Presumably it is defined as

`sensor = sensor_input.value` since it's later indexed by integer (e.g. `sensor[1]`) and there is no `getindex` defined for `Input`

**Comment by shashi** [comment]
I don't see a variable called `sensor`, I assume it's `sensors`. Since `read_sensors()` returns a vector, when you call `lift` on this signal, you will get a 2-element array of left and right readings. The variable `sensors` is the argument to the functions `v_left` and `v_right` which is passed in to lift. This is why `getindex` will be defined on the `sensors` variable.

**Comment by milktrader** [comment]
Correct on `sensors` vs `sensor`. The example works with the long form of `lift` (vs the macro), so I'll close this. Thanks!
